--------------------------------------------------------
--  File created - Wednesday-April-12-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTI_PEMESANAN
--------------------------------------------------------

  CREATE TABLE "SIA"."PTI_PEMESANAN" 
   (	"ID_MEMBER" VARCHAR2(20 BYTE), 
	"ID_KURIR" VARCHAR2(20 BYTE), 
	"TANGGAL" DATE, 
	"ASAL" VARCHAR2(150 BYTE), 
	"TUJUAN" VARCHAR2(150 BYTE), 
	"JARAK" NUMBER, 
	"BARANG" VARCHAR2(50 BYTE), 
	"BIAYA" NUMBER, 
	"STATUS" VARCHAR2(1 BYTE), 
	"ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SIA.PTI_PEMESANAN
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PTI_PEMESANAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIA"."PTI_PEMESANAN_PK" ON "SIA"."PTI_PEMESANAN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PTI_PEMESANAN
--------------------------------------------------------

  ALTER TABLE "SIA"."PTI_PEMESANAN" ADD CONSTRAINT "PTI_PEMESANAN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SIA"."PTI_PEMESANAN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_PEMESANAN" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_PEMESANAN" MODIFY ("BIAYA" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_PEMESANAN" MODIFY ("BARANG" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_PEMESANAN" MODIFY ("JARAK" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_PEMESANAN" MODIFY ("TUJUAN" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_PEMESANAN" MODIFY ("ASAL" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_PEMESANAN" MODIFY ("TANGGAL" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_PEMESANAN" MODIFY ("ID_MEMBER" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PTI_PEMESANAN
--------------------------------------------------------

  ALTER TABLE "SIA"."PTI_PEMESANAN" ADD CONSTRAINT "PTI_PEMESANAN_FK1" FOREIGN KEY ("ID_MEMBER")
	  REFERENCES "SIA"."PTI_PELANGGAN" ("ID") ENABLE;
  ALTER TABLE "SIA"."PTI_PEMESANAN" ADD CONSTRAINT "PTI_PEMESANAN_FK2" FOREIGN KEY ("ID_KURIR")
	  REFERENCES "SIA"."PTI_KURIR" ("ID") ENABLE;
