--------------------------------------------------------
--  File created - Wednesday-April-12-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTI_KURIR
--------------------------------------------------------

  CREATE TABLE "SIA"."PTI_KURIR" 
   (	"ID" VARCHAR2(8 BYTE), 
	"NAMA" VARCHAR2(25 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"NO_TLP" NUMBER, 
	"ALAMAT" VARCHAR2(150 BYTE), 
	"PASSWORD" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SIA.PTI_KURIR
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PTI_KURIR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIA"."PTI_KURIR_PK" ON "SIA"."PTI_KURIR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PTI_KURIR_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIA"."PTI_KURIR_EMAIL" ON "SIA"."PTI_KURIR" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PTI_KURIR_TLP
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIA"."PTI_KURIR_TLP" ON "SIA"."PTI_KURIR" ("NO_TLP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PTI_KURIR
--------------------------------------------------------

  ALTER TABLE "SIA"."PTI_KURIR" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_KURIR" ADD CONSTRAINT "PTI_KURIR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SIA"."PTI_KURIR" MODIFY ("NO_TLP" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_KURIR" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_KURIR" MODIFY ("NAMA" NOT NULL ENABLE);
  ALTER TABLE "SIA"."PTI_KURIR" MODIFY ("ID" NOT NULL ENABLE);
